name: Install JDK and Ducky Image
on: [push, pull_request]
jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code (optional)
      # - uses: actions/checkout@v2
      
      # Step 1: Install OpenJDK
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
      # Step 2: Download Ducky image
      - name: Download Ducky image
        run: |
          curl --fail -sS -O https://boonk8812.github.io/actionsimages/ducky@v1.img -o ducky@v1.img
          echo "Downloaded Ducky image successfully" >> $GITHUB_WORKFLOW_LOG.txt

      # Step 3: Save JDK as an artifact (renamed)
      - name: Upload JDK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: custom-jdk
          path: /usr/lib/jvm/java-11-openjdk-amd64

      # Step 4: Save Ducky image as an artifact
      - name: Upload Ducky image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: custom-ducky-image
          path: ducky@v1.img
